"""empty message

Revision ID: 99ac0d58ef2f
Revises: a266c819a4df
Create Date: 2023-11-09 13:40:34.582123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ac0d58ef2f'
down_revision = 'a266c819a4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
